services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      EDITOR: vim
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/myapp
      - bundle_volume:/usr/local/bundle
    ports:
      - '3000:3000'
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
volumes:
  postgres_volume:
  bundle_volume:
  redis_data:
